### ISSUE TITLE
Migrate away from Wiki

### ISSUE THREAD

**Issue by koppor** [dirigiblelabs/dirigiblelabs#8]
The README.md links to <https://wiki.eclipse.org/Dirigible/DirigibleLabs>.

That wiki will be read-only:

> Notice: this Wiki will be going read only early in 2024 and edits will no longer be possible. Please see: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/wikis/Wiki-shutdown-plan for the plan.

One "just" needs to migrate to a (GitHub) wiki alongside the project.

**Comment by delchev** [comment]
Fixed with: https://github.com/dirigiblelabs/dirigiblelabs/commit/ecc8177b314a75724bc0f788c5571b3d902793d6
